### PR TITLE
control/collect-jmx: fix handling of process-specific queries

### PR DESCRIPTION
**Pull request by masiulaniec**
Fixes issue #5.

### CODE REVIEW

**Comment by andredasilvapinto** [comment]
Cool!
Wouldn't it be better to have a test for this?

**Comment by masiulaniec** [comment]
Good point; stay tuned.

**Comment by pharaujo** [comment]
Just noticed this pull request. @masiulaniec, did you get a chance to write the test?

**Comment by pharaujo** [comment]
We could also probably use the test from #11 for this as it supposedly solves the same problem, right?

**Comment by pharaujo** [comment]
Just tried the relevant test from @andredasilvapinto . The following test fails before and passes after applying this pull request:

```diff
diff --git a/cmd/tsp-controller/control/collect-jmx/control_test.go b/cmd/tsp-controller/control/collect-jmx/control_test.go
index b1dcc75..a00b00d 100644
--- a/cmd/tsp-controller/control/collect-jmx/control_test.go
+++ b/cmd/tsp-controller/control/collect-jmx/control_test.go
@@ -722,3 +722,35 @@ func makeConfig(v interface{}) *config.Config {
        }
        panic("internal error")
 }
+
+func TestView(t *testing.T) {
+       cfgStr :=
+               `<config>
+                       <hostgroup id="foo">
+                               <cluster id="foo.live">
+                                       <host id="foo001">
+                                               <process id="foo.process"/>
+                                       </host>
+                               </cluster>
+                       </hostgroup>
+                       <querygroup id="q" targets="foo">
+                               <query id="x" on="X:name=*" attributes="K,L"/>
+                       </querygroup>
+               </config>`
+
+       cfg, _ := config.Decode(strings.NewReader(cfgStr))
+
+       hdl := &handler{
+               config: cfg,
+       }
+
+       view, _ := hdl.View(&Key{
+               Host:    "foo002",
+               Process: "foo",
+       })
+
+       // Make sure we are not matching process names with any other targets (in this case hostgroup foo)
+       if len(view.Objects) > 0 {
+               t.Errorf("invalid view resolution\ngot:  %+v\nwant: []", view.Objects)
+       }
+}
```

**Comment by masiulaniec** [comment]
Sorry about inactivity on this. The test looks good, wanna submit a diff?

**Comment by pharaujo** [comment]
I can't add to this pull request. How do you suggest I submit the patch?
You can copy the diff in https://github.com/betfair/opentsp/pull/12#issuecomment-120435817 to a `issue-5.patch` and do a `patch -p1 < issue-5.patch` on your branch.

**Comment by masiulaniec** [comment]
After a bit of a struggle, I think I managed to update the diff (I suck at Github).

Does it look good to you?

**Pull request merged**
